# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0f83c1abe19b7f388fcf0a26a6b092ba04f41922afc9bda8bd2287a391acf2170cb83e35b23ec65a60642c8577bfcac37a7b371488f436c6628be2bd9c543f1d

test:
  secret_key_base: ff01b65e0c27c07612ffc87158958ec0a6f93624dcaa95e26fc6ba18848e8af69e96cc799629f689deb241ce7f23ab28e855c818a39774b904252643292ebb93

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
